// <auto-generated />
using InternshipManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternshipManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260602071837_AddPasswordToStudent")]
    partial class AddPasswordToStudent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InternshipManagement.Models.Enterprise", b =>
                {
                    b.Property<int>("MaDN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaDN"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("longtext");

                    b.Property<string>("TenDN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaDN");

                    b.ToTable("Enterprises");
                });

            modelBuilder.Entity("InternshipManagement.Models.InternshipRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Diem")
                        .HasColumnType("double");

                    b.Property<string>("FileBaoCao")
                        .HasColumnType("longtext");

                    b.Property<string>("MSSV")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MaDN")
                        .HasColumnType("int");

                    b.Property<string>("MaGV")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NguoiHuongDanDN")
                        .HasColumnType("longtext");

                    b.Property<string>("NhanXetGV")
                        .HasColumnType("longtext");

                    b.Property<string>("ThoiGianThucTap")
                        .HasColumnType("longtext");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MSSV");

                    b.HasIndex("MaDN");

                    b.HasIndex("MaGV");

                    b.ToTable("InternshipRegistrations");
                });

            modelBuilder.Entity("InternshipManagement.Models.Lecturer", b =>
                {
                    b.Property<string>("MaGV")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Khoa")
                        .HasColumnType("longtext");

                    b.HasKey("MaGV");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("InternshipManagement.Models.Student", b =>
                {
                    b.Property<string>("MSSV")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KhoaHoc")
                        .HasColumnType("longtext");

                    b.Property<string>("Lop")
                        .HasColumnType("longtext");

                    b.Property<string>("Nganh")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MSSV");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("InternshipManagement.Models.InternshipRegistration", b =>
                {
                    b.HasOne("InternshipManagement.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("MSSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternshipManagement.Models.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("MaDN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternshipManagement.Models.Lecturer", "Lecturer")
                        .WithMany()
                        .HasForeignKey("MaGV");

                    b.Navigation("Enterprise");

                    b.Navigation("Lecturer");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
